name = "thikanadhablawebsitedeploy2026testing"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./"
binding = "ASSETS"
not_found_handling = "none"
